/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageClassificazione;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3ZFRp0XpS79A= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3ZFRp0XpS79A= >>
// ----------- >>
private class Classificazione {
    // ----------- << attribute.annotations@AAAAAAF3ZIDiNH7Fe+Y= >>
    // ----------- >>
    private Segmento segmento;

    // ----------- << attribute.annotations@AAAAAAF3ZIDvWH7LXak= >>
    // ----------- >>
    private Genere genere;

    // ----------- << attribute.annotations@AAAAAAF3ZID8ln7RkdM= >>
    // ----------- >>
    private Sottogenere sottoGenere;

    // ----------- << attribute.annotations@AAAAAAF3ZIEKn37Xjlg= >>
    // ----------- >>
    private Tipo tipo;

    // ----------- << attribute.annotations@AAAAAAF3ZIEZ6n7dFGs= >>
    // ----------- >>
    private Sottotipo sottoTipo;

    // ----------- << attribute.annotations@AAAAAAF3clk/icq9948= >>
    // ----------- >>
    private Segmento ;

    // ----------- << attribute.annotations@AAAAAAF3clrVn8/onoI= >>
    // ----------- >>
    private Genere ;

    // ----------- << attribute.annotations@AAAAAAF3clw/X9S7isg= >>
    // ----------- >>
    private Sottogenere ;

    // ----------- << attribute.annotations@AAAAAAF3cl2mKtjBKPg= >>
    // ----------- >>
    private Tipo ;

    // ----------- << attribute.annotations@AAAAAAF3cl+WKN7/IVA= >>
    // ----------- >>
    private Sottotipo ;

    private Segmento getSegmento() {
        return segmento;
    }

    private Genere getGenere() {
        return genere;
    }

    private Sottogenere getSottoGenere() {
        return sottoGenere;
    }

    private Tipo getTipo() {
        return tipo;
    }

    private Sottotipo getSottoTipo() {
        return sottoTipo;
    }

    public Segmento get() {
        return ;
    }

    public Genere get() {
        return ;
    }

    public Sottogenere get() {
        return ;
    }

    public Tipo get() {
        return ;
    }

    public Sottotipo get() {
        return ;
    }

    private void setSegmento(Segmento segmento) {
        this.segmento = segmento;
    }

    private void setGenere(Genere genere) {
        this.genere = genere;
    }

    private void setSottoGenere(Sottogenere sottoGenere) {
        this.sottoGenere = sottoGenere;
    }

    private void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }

    private void setSottoTipo(Sottotipo sottoTipo) {
        this.sottoTipo = sottoTipo;
    }

    public void set(Segmento ) {
        this. = ;
    }

    public void set(Genere ) {
        this. = ;
    }

    public void set(Sottogenere ) {
        this. = ;
    }

    public void set(Tipo ) {
        this. = ;
    }

    public void set(Sottotipo ) {
        this. = ;
    }

    public void link(Segmento _) {
        set(_);
    }

    public void link(Genere _) {
        set(_);
    }

    public void link(Sottogenere _) {
        set(_);
    }

    public void link(Tipo _) {
        set(_);
    }

    public void link(Sottotipo _) {
        set(_);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }

    /**
    * @param segment 
    * @param genre 
    * @param subGen 
    * @param type 
    * @param subType
    */

    // ----------- << method.annotations@AAAAAAF3ZIMl/H7uNIs= >>
    // ----------- >>
    public Classificazione(Segmento segment, Genere genre, Sottogenere subGen, Tipo type, Sottotipo subType) {
    // ----------- << method.body@AAAAAAF3ZIMl/H7uNIs= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3ZFRp0XpS79A= >>
// ----------- >>
}