/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageClassificazione;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3ZF8m3nryg44= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3ZF8m3nryg44= >>
// ----------- >>
public class Genere {
    // ----------- << attribute.annotations@AAAAAAF3ZF9OvnsdY84= >>
    // ----------- >>
    private String idGenere;

    // ----------- << attribute.annotations@AAAAAAF3ZF9aWnsjWRI= >>
    // ----------- >>
    private String nomeGenere;

    private String getIdGenere() {
        return idGenere;
    }

    private String getNomeGenere() {
        return nomeGenere;
    }

    private void setIdGenere(String idGenere) {
        this.idGenere = idGenere;
    }

    private void setNomeGenere(String nomeGenere) {
        this.nomeGenere = nomeGenere;
    }

    // ----------- << method.annotations@AAAAAAF3ZF/Qo3srafk= >>
    // ----------- >>
    public Genere() {
    // ----------- << method.body@AAAAAAF3ZF/Qo3srafk= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZF/dyHsxiII= >>
    // ----------- >>
    public String getIdGenere() {
    // ----------- << method.body@AAAAAAF3ZF/dyHsxiII= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZF/scHs3rS4= >>
    // ----------- >>
    public String getNomeGenere() {
    // ----------- << method.body@AAAAAAF3ZF/scHs3rS4= >>
    // ----------- >>
    }
    /**
    * @param idGenre
    */

    // ----------- << method.annotations@AAAAAAF3ZF/5Jns977E= >>
    // ----------- >>
    public void setIdGenere(String idGenre) {
    // ----------- << method.body@AAAAAAF3ZF/5Jns977E= >>
    // ----------- >>
    }
    /**
    * @param nameGenre
    */

    // ----------- << method.annotations@AAAAAAF3ZGAGk3tDtwg= >>
    // ----------- >>
    public void setNomeGenere(void nameGenre) {
    // ----------- << method.body@AAAAAAF3ZGAGk3tDtwg= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3ZF8m3nryg44= >>
// ----------- >>
}