/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageClassificazione;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3ZFo3nHqAfDE= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3ZFo3nHqAfDE= >>
// ----------- >>
public class Segmento {
    // ----------- << attribute.annotations@AAAAAAF3ZFuGqHqsGXg= >>
    // ----------- >>
    private String idSegmento;

    // ----------- << attribute.annotations@AAAAAAF3ZFuY3Xqyp98= >>
    // ----------- >>
    private String nomeSegmento;

    private String getIdSegmento() {
        return idSegmento;
    }

    private String getNomeSegmento() {
        return nomeSegmento;
    }

    private void setIdSegmento(String idSegmento) {
        this.idSegmento = idSegmento;
    }

    private void setNomeSegmento(String nomeSegmento) {
        this.nomeSegmento = nomeSegmento;
    }

    // ----------- << method.annotations@AAAAAAF3ZFy5Nnq6R3w= >>
    // ----------- >>
    public Segmento() {
    // ----------- << method.body@AAAAAAF3ZFy5Nnq6R3w= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZFzSEnrBGpw= >>
    // ----------- >>
    public String getIdSegmento() {
    // ----------- << method.body@AAAAAAF3ZFzSEnrBGpw= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZFzet3rHRMc= >>
    // ----------- >>
    public String getNomeSegmento() {
    // ----------- << method.body@AAAAAAF3ZFzet3rHRMc= >>
    // ----------- >>
    }
    /**
    * @param idSegment
    */

    // ----------- << method.annotations@AAAAAAF3ZFzqUXrNKHw= >>
    // ----------- >>
    public void setIdSegmento(String idSegment) {
    // ----------- << method.body@AAAAAAF3ZFzqUXrNKHw= >>
    // ----------- >>
    }
    /**
    * @param nameSegment
    */

    // ----------- << method.annotations@AAAAAAF3ZFz3fXrTqV0= >>
    // ----------- >>
    public void setNomeSegmento(String nameSegment) {
    // ----------- << method.body@AAAAAAF3ZFz3fXrTqV0= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3ZFo3nHqAfDE= >>
// ----------- >>
}