/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageClassificazione;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3ZHZAe31oZF0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3ZHZAe31oZF0= >>
// ----------- >>
public class Sottogenere {
    // ----------- << attribute.annotations@AAAAAAF3ZHaw4H2VDxc= >>
    // ----------- >>
    private String idSottogenere;

    // ----------- << attribute.annotations@AAAAAAF3ZHbDDX2bKf8= >>
    // ----------- >>
    private String nomeSottogenere;

    private String getIdSottogenere() {
        return idSottogenere;
    }

    private String getNomeSottogenere() {
        return nomeSottogenere;
    }

    private void setIdSottogenere(String idSottogenere) {
        this.idSottogenere = idSottogenere;
    }

    private void setNomeSottogenere(String nomeSottogenere) {
        this.nomeSottogenere = nomeSottogenere;
    }

    // ----------- << method.annotations@AAAAAAF3ZHffpX2p4eE= >>
    // ----------- >>
    public Sottogenere() {
    // ----------- << method.body@AAAAAAF3ZHffpX2p4eE= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZHfyNX2vs8k= >>
    // ----------- >>
    public String getIdSottogenere() {
    // ----------- << method.body@AAAAAAF3ZHfyNX2vs8k= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZHgDW321d3o= >>
    // ----------- >>
    public String getNomeSottogenere() {
    // ----------- << method.body@AAAAAAF3ZHgDW321d3o= >>
    // ----------- >>
    }
    /**
    * @param idSubGenre
    */

    // ----------- << method.annotations@AAAAAAF3ZHgXHX27DWA= >>
    // ----------- >>
    public void setIdSottogenere(String idSubGenre) {
    // ----------- << method.body@AAAAAAF3ZHgXHX27DWA= >>
    // ----------- >>
    }
    /**
    * @param nameSubGenre
    */

    // ----------- << method.annotations@AAAAAAF3ZHhIan3ByA4= >>
    // ----------- >>
    public void setNomeSottogenere(String nameSubGenre) {
    // ----------- << method.body@AAAAAAF3ZHhIan3ByA4= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3ZHZAe31oZF0= >>
// ----------- >>
}