/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageClassificazione;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3ZH2KZ35Qb7Y= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3ZH2KZ35Qb7Y= >>
// ----------- >>
public class Sottotipo {
    // ----------- << attribute.annotations@AAAAAAF3ZH3f8n58bHs= >>
    // ----------- >>
    private String idSottotipo;

    // ----------- << attribute.annotations@AAAAAAF3ZH4Wo36Dghc= >>
    // ----------- >>
    private String nomeSottotipo;

    private String getIdSottotipo() {
        return idSottotipo;
    }

    private String getNomeSottotipo() {
        return nomeSottotipo;
    }

    private void setIdSottotipo(String idSottotipo) {
        this.idSottotipo = idSottotipo;
    }

    private void setNomeSottotipo(String nomeSottotipo) {
        this.nomeSottotipo = nomeSottotipo;
    }

    // ----------- << method.annotations@AAAAAAF3ZH4t4n6JZQU= >>
    // ----------- >>
    public Sottotipo() {
    // ----------- << method.body@AAAAAAF3ZH4t4n6JZQU= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZH5FfH6PIao= >>
    // ----------- >>
    public String getIdSottotipo() {
    // ----------- << method.body@AAAAAAF3ZH5FfH6PIao= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZH5Wd36VCTs= >>
    // ----------- >>
    public String getNomeSottotipo() {
    // ----------- << method.body@AAAAAAF3ZH5Wd36VCTs= >>
    // ----------- >>
    }
    /**
    * @param idSubType
    */

    // ----------- << method.annotations@AAAAAAF3ZH5rTX6bpWc= >>
    // ----------- >>
    public void setIdSottotipo(String idSubType) {
    // ----------- << method.body@AAAAAAF3ZH5rTX6bpWc= >>
    // ----------- >>
    }
    /**
    * @param nameSubType
    */

    // ----------- << method.annotations@AAAAAAF3ZH6C0H6hzNg= >>
    // ----------- >>
    public void setNomeSottotipo(String nameSubType) {
    // ----------- << method.body@AAAAAAF3ZH6C0H6hzNg= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3ZH2KZ35Qb7Y= >>
// ----------- >>
}