/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageClassificazione;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3ZHqzGX3eJkk= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3ZHqzGX3eJkk= >>
// ----------- >>
public class Tipo {
    // ----------- << attribute.annotations@AAAAAAF3ZHr7SH4Kqd8= >>
    // ----------- >>
    private String idTipo;

    // ----------- << attribute.annotations@AAAAAAF3ZHsH1H4QYMI= >>
    // ----------- >>
    private String nomeTipo;

    private String getIdTipo() {
        return idTipo;
    }

    private String getNomeTipo() {
        return nomeTipo;
    }

    private void setIdTipo(String idTipo) {
        this.idTipo = idTipo;
    }

    private void setNomeTipo(String nomeTipo) {
        this.nomeTipo = nomeTipo;
    }

    // ----------- << method.annotations@AAAAAAF3ZHtgN34YgxM= >>
    // ----------- >>
    public Tipo() {
    // ----------- << method.body@AAAAAAF3ZHtgN34YgxM= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZHtt6H4eMXU= >>
    // ----------- >>
    public String getIdTipo() {
    // ----------- << method.body@AAAAAAF3ZHtt6H4eMXU= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZHuZe34kG8M= >>
    // ----------- >>
    public String getNomeTipo() {
    // ----------- << method.body@AAAAAAF3ZHuZe34kG8M= >>
    // ----------- >>
    }
    /**
    * @param idType
    */

    // ----------- << method.annotations@AAAAAAF3ZHvDGX4sbzk= >>
    // ----------- >>
    public void setIdTipo(String idType) {
    // ----------- << method.body@AAAAAAF3ZHvDGX4sbzk= >>
    // ----------- >>
    }
    /**
    * @param nameType
    */

    // ----------- << method.annotations@AAAAAAF3ZHvQgX4yVSw= >>
    // ----------- >>
    public void setNomeTipo(String nameType) {
    // ----------- << method.body@AAAAAAF3ZHvQgX4yVSw= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3ZHqzGX3eJkk= >>
// ----------- >>
}