/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageVendite;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3Y2Y3IAFk1Hw= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3Y2Y3IAFk1Hw= >>
// ----------- >>
public class Prevendite {
    // ----------- << attribute.annotations@AAAAAAF3Y2dlzQGQ53Y= >>
    // ----------- >>
    private LocalDate dataOraInizioPrevendite;

    // ----------- << attribute.annotations@AAAAAAF3Y2d10gGWMn4= >>
    // ----------- >>
    private LocalDate dataOraFinePrevendite;

    // ----------- << attribute.annotations@AAAAAAF3Y24pcQGlvFQ= >>
    // ----------- >>
    private String nomePrevendita;

    private LocalDate getDataOraInizioPrevendite() {
        return dataOraInizioPrevendite;
    }

    private LocalDate getDataOraFinePrevendite() {
        return dataOraFinePrevendite;
    }

    private String getNomePrevendita() {
        return nomePrevendita;
    }

    private void setDataOraInizioPrevendite(LocalDate dataOraInizioPrevendite) {
        this.dataOraInizioPrevendite = dataOraInizioPrevendite;
    }

    private void setDataOraFinePrevendite(LocalDate dataOraFinePrevendite) {
        this.dataOraFinePrevendite = dataOraFinePrevendite;
    }

    private void setNomePrevendita(String nomePrevendita) {
        this.nomePrevendita = nomePrevendita;
    }

    // ----------- << method.annotations@AAAAAAF3Y7jw6XjVbQU= >>
    // ----------- >>
    public Prevendite() {
    // ----------- << method.body@AAAAAAF3Y7jw6XjVbQU= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3Y28NxwGu3jM= >>
    // ----------- >>
    public LocalDate getDataOraInizioPrevendite() {
    // ----------- << method.body@AAAAAAF3Y28NxwGu3jM= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3Y28bBgG0k6o= >>
    // ----------- >>
    public LocalDate getDataOraFinePrevendite() {
    // ----------- << method.body@AAAAAAF3Y28bBgG0k6o= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3Y28oiwG6YFI= >>
    // ----------- >>
    public String getNomePrevendita() {
    // ----------- << method.body@AAAAAAF3Y28oiwG6YFI= >>
    // ----------- >>
    }
    /**
    * @param dataOraInizioPre
    */

    // ----------- << method.annotations@AAAAAAF3Y2816wHAMhI= >>
    // ----------- >>
    public void setDataOraInizioPrevendite(LocalDate dataOraInizioPre) {
    // ----------- << method.body@AAAAAAF3Y2816wHAMhI= >>
    // ----------- >>
    }
    /**
    * @param dataOraFinePre
    */

    // ----------- << method.annotations@AAAAAAF3Y29bsQHGeNY= >>
    // ----------- >>
    public void setDataOraFinePrevendite(LocalDate dataOraFinePre) {
    // ----------- << method.body@AAAAAAF3Y29bsQHGeNY= >>
    // ----------- >>
    }
    /**
    * @param nomePre
    */

    // ----------- << method.annotations@AAAAAAF3Y2+J9wHNuGM= >>
    // ----------- >>
    public void setNomePrevendita(String nomePre) {
    // ----------- << method.body@AAAAAAF3Y2+J9wHNuGM= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3Y2Y3IAFk1Hw= >>
// ----------- >>
}