/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageVendite;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3Y5xawHfGk2I= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3Y5xawHfGk2I= >>
// ----------- >>
public class VenditePubbliche {
    // ----------- << attribute.annotations@AAAAAAF3Y58rIXfyfpI= >>
    // ----------- >>
    private LocalDate dataOraInizio;

    // ----------- << attribute.annotations@AAAAAAF3Y584DXf4710= >>
    // ----------- >>
    private LocalDate dataOraFine;

    private LocalDate getDataOraInizio() {
        return dataOraInizio;
    }

    public LocalDate getDataOraFine() {
        return dataOraFine;
    }

    private void setDataOraInizio(LocalDate dataOraInizio) {
        this.dataOraInizio = dataOraInizio;
    }

    public void setDataOraFine(LocalDate dataOraFine) {
        this.dataOraFine = dataOraFine;
    }

    // ----------- << method.annotations@AAAAAAF3Y7mVsHji0V0= >>
    // ----------- >>
    public VenditePubbliche() {
    // ----------- << method.body@AAAAAAF3Y7mVsHji0V0= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3Y6AcyHgBdgA= >>
    // ----------- >>
    public LocalDate getDataOraInizio() {
    // ----------- << method.body@AAAAAAF3Y6AcyHgBdgA= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3Y6AodHgHTTs= >>
    // ----------- >>
    public LocalDate getDataOraFine() {
    // ----------- << method.body@AAAAAAF3Y6AodHgHTTs= >>
    // ----------- >>
    }
    /**
    * @param dataOraStart
    */

    // ----------- << method.annotations@AAAAAAF3Y6AzfXgNHEk= >>
    // ----------- >>
    public void setDataOraInizio(LocalDate dataOraStart) {
    // ----------- << method.body@AAAAAAF3Y6AzfXgNHEk= >>
    // ----------- >>
    }
    /**
    * @param dataOraEnd
    */

    // ----------- << method.annotations@AAAAAAF3Y6BCdXgTl6U= >>
    // ----------- >>
    public void setDataOraFine(LocalDate dataOraEnd) {
    // ----------- << method.body@AAAAAAF3Y6BCdXgTl6U= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3Y5xawHfGk2I= >>
// ----------- >>
}