/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package ModelUMLTicketMaster;

import java.util.*;
import java.time.*;


import EmbeddedPackage.Embedded;
import PackageClassificazione.Classificazione;
import PackageDataEvento.DataEvento;
import PackageLinks.Link;
import PackageVendite.Vendite;
// ----------- << imports@AAAAAAF3YyVBev/bYtw= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3YyVBev/bYtw= >>
// ----------- >>
public class Eventi {
    // ----------- << attribute.annotations@AAAAAAF3YymFYgAM4gQ= >>
    // ----------- >>
    private String nomeEvento;

    // ----------- << attribute.annotations@AAAAAAF3YynrEQAVq+8= >>
    // ----------- >>
    private String tipoEvento;

    // ----------- << attribute.annotations@AAAAAAF3YyqGpAAenfs= >>
    // ----------- >>
    private String idEvento;

    // ----------- << attribute.annotations@AAAAAAF3YyszQAAn7is= >>
    // ----------- >>
    private String urlEvento;

    // ----------- << attribute.annotations@AAAAAAF3ZIbNPX8bP7Q= >>
    // ----------- >>
    private Vendite vendite;

    // ----------- << attribute.annotations@AAAAAAF3ZIbeaX8hC3I= >>
    // ----------- >>
    private DataEvento dataEvento;

    // ----------- << attribute.annotations@AAAAAAF3ZIbtmH8nV8Y= >>
    // ----------- >>
    private Classificazione classificazione;

    // ----------- << attribute.annotations@AAAAAAF3cmbwgvaaoM4= >>
    // ----------- >>
    private String infoEvento;

    // ----------- << attribute.annotations@AAAAAAF3ZIQU9X737TM= >>
    // ----------- >>
    private String pleaseNote;

    // ----------- << attribute.annotations@AAAAAAF3ZI+Mcn/lZCM= >>
    // ----------- >>
    private FasciaDiPrezzo fasciaDiPrezzo;

    // ----------- << attribute.annotations@AAAAAAF3ZJSRa4BApIM= >>
    // ----------- >>
    private MappaPostoUtente postoUtente;

    // ----------- << attribute.annotations@AAAAAAF3ZJhkfYCd9r4= >>
    // ----------- >>
    private MassimoBiglietti massimoBiglietti;

    // ----------- << attribute.annotations@AAAAAAF3ZMocYoHotow= >>
    // ----------- >>
    private Link linkEvent;

    // ----------- << attribute.annotations@AAAAAAF3asRxUjMrjnU= >>
    // ----------- >>
    private Embedded embedded;

    // ----------- << attribute.annotations@AAAAAAF3ckYNibiDh4M= >>
    // ----------- >>
    private Vendite ;

    // ----------- << attribute.annotations@AAAAAAF3clNznsQjSLM= >>
    // ----------- >>
    private DataEvento ;

    // ----------- << attribute.annotations@AAAAAAF3cmHwx+tCLhQ= >>
    // ----------- >>
    private Set<Classificazione>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF3cmmxjwa8f5U= >>
    // ----------- >>
    private Set<FasciaDiPrezzo>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF3cm/wnBK3WqQ= >>
    // ----------- >>
    private MappaPostoUtente ;

    // ----------- << attribute.annotations@AAAAAAF3cnI1/BzN6QY= >>
    // ----------- >>
    private MassimoBiglietti ;

    // ----------- << attribute.annotations@AAAAAAF3cojRcVBY5s8= >>
    // ----------- >>
    private Link ;

    // ----------- << attribute.annotations@AAAAAAF3cs4dwnDJLu0= >>
    // ----------- >>
    private Embedded ;

    private String getNomeEvento() {
        return nomeEvento;
    }

    private String getTipoEvento() {
        return tipoEvento;
    }

    private String getIdEvento() {
        return idEvento;
    }

    private String getUrlEvento() {
        return urlEvento;
    }

    private Vendite getVendite() {
        return vendite;
    }

    private DataEvento getDataEvento() {
        return dataEvento;
    }

    private Classificazione getClassificazione() {
        return classificazione;
    }

    private String getInfoEvento() {
        return infoEvento;
    }

    private String getPleaseNote() {
        return pleaseNote;
    }

    private FasciaDiPrezzo getFasciaDiPrezzo() {
        return fasciaDiPrezzo;
    }

    private MappaPostoUtente getPostoUtente() {
        return postoUtente;
    }

    private MassimoBiglietti getMassimoBiglietti() {
        return massimoBiglietti;
    }

    private Link getLinkEvent() {
        return linkEvent;
    }

    private Embedded getEmbedded() {
        return embedded;
    }

    public Vendite get() {
        return ;
    }

    public DataEvento get() {
        return ;
    }

    public Set<Classificazione> get() {
        return ;
    }

    public Set<FasciaDiPrezzo> get() {
        return ;
    }

    public MappaPostoUtente get() {
        return ;
    }

    public MassimoBiglietti get() {
        return ;
    }

    public Link get() {
        return ;
    }

    public Embedded get() {
        return ;
    }

    private void setNomeEvento(String nomeEvento) {
        this.nomeEvento = nomeEvento;
    }

    private void setTipoEvento(String tipoEvento) {
        this.tipoEvento = tipoEvento;
    }

    private void setIdEvento(String idEvento) {
        this.idEvento = idEvento;
    }

    private void setUrlEvento(String urlEvento) {
        this.urlEvento = urlEvento;
    }

    private void setVendite(Vendite vendite) {
        this.vendite = vendite;
    }

    private void setDataEvento(DataEvento dataEvento) {
        this.dataEvento = dataEvento;
    }

    private void setClassificazione(Classificazione classificazione) {
        this.classificazione = classificazione;
    }

    private void setInfoEvento(String infoEvento) {
        this.infoEvento = infoEvento;
    }

    private void setPleaseNote(String pleaseNote) {
        this.pleaseNote = pleaseNote;
    }

    private void setFasciaDiPrezzo(FasciaDiPrezzo fasciaDiPrezzo) {
        this.fasciaDiPrezzo = fasciaDiPrezzo;
    }

    private void setPostoUtente(MappaPostoUtente postoUtente) {
        this.postoUtente = postoUtente;
    }

    private void setMassimoBiglietti(MassimoBiglietti massimoBiglietti) {
        this.massimoBiglietti = massimoBiglietti;
    }

    private void setLinkEvent(Link linkEvent) {
        this.linkEvent = linkEvent;
    }

    private void setEmbedded(Embedded embedded) {
        this.embedded = embedded;
    }

    public void set(Vendite ) {
        this. = ;
    }

    public void set(DataEvento ) {
        this. = ;
    }

    public void set(MappaPostoUtente ) {
        this. = ;
    }

    public void set(MassimoBiglietti ) {
        this. = ;
    }

    public void set(Link ) {
        this. = ;
    }

    public void set(Embedded ) {
        this. = ;
    }

    public void link(Vendite _) {
        set(_);
    }

    public void link(DataEvento _) {
        set(_);
    }

    public void link(Classificazione _) {
        if (_ != null) {
            get().add(_);
        }
    }

    public void link(FasciaDiPrezzo _) {
        if (_ != null) {
            get().add(_);
        }
    }

    public void link(MappaPostoUtente _) {
        set(_);
    }

    public void link(MassimoBiglietti _) {
        set(_);
    }

    public void link(Link _) {
        set(_);
    }

    public void link(Embedded _) {
        set(_);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }

    public void unlink(Classificazione _) {
        if (_ != null) {
            get().remove(_);
        }
    }

    public void unlink(Iterator<Classificazione> it) {
        it.remove();
    }

    public void unlink(FasciaDiPrezzo _) {
        if (_ != null) {
            get().remove(_);
        }
    }

    public void unlink(Iterator<FasciaDiPrezzo> it) {
        it.remove();
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }

    // ----------- << method.annotations@AAAAAAF3Y7oKMnjtvWs= >>
    // ----------- >>
    public void Evento() {
    // ----------- << method.body@AAAAAAF3Y7oKMnjtvWs= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3Yyy8aQAx6ps= >>
    // ----------- >>
    public String getNomeEvento() {
    // ----------- << method.body@AAAAAAF3Yyy8aQAx6ps= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3YyzLvgA3rCE= >>
    // ----------- >>
    public String getTipoEvento() {
    // ----------- << method.body@AAAAAAF3YyzLvgA3rCE= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3YyzivwA9gjQ= >>
    // ----------- >>
    public String getIdEvento() {
    // ----------- << method.body@AAAAAAF3YyzivwA9gjQ= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3Yyz4MwBDskY= >>
    // ----------- >>
    public String getUrlEvento() {
    // ----------- << method.body@AAAAAAF3Yyz4MwBDskY= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3cmfuB/ycKB0= >>
    // ----------- >>
    public String getInfoEvento() {
    // ----------- << method.body@AAAAAAF3cmfuB/ycKB0= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZISSL37/RyE= >>
    // ----------- >>
    public String getPleaseNote() {
    // ----------- << method.body@AAAAAAF3ZISSL37/RyE= >>
    // ----------- >>
    }
    /**
    * @param nome
    */

    // ----------- << method.annotations@AAAAAAF3Yy0EVwBJhrs= >>
    // ----------- >>
    public void setNomeEvento(String nome) {
    // ----------- << method.body@AAAAAAF3Yy0EVwBJhrs= >>
    // ----------- >>
    }
    /**
    * @param tipo
    */

    // ----------- << method.annotations@AAAAAAF3Yy0PjgBP0Aw= >>
    // ----------- >>
    public void setTipoEvento(String tipo) {
    // ----------- << method.body@AAAAAAF3Yy0PjgBP0Aw= >>
    // ----------- >>
    }
    /**
    * @param id
    */

    // ----------- << method.annotations@AAAAAAF3Yy0svwBVSfU= >>
    // ----------- >>
    public void setIdEvento(String id) {
    // ----------- << method.body@AAAAAAF3Yy0svwBVSfU= >>
    // ----------- >>
    }
    /**
    * @param url
    */

    // ----------- << method.annotations@AAAAAAF3Yy0/yQBbJ14= >>
    // ----------- >>
    public void setUrlEvento(String url) {
    // ----------- << method.body@AAAAAAF3Yy0/yQBbJ14= >>
    // ----------- >>
    }
    /**
    * @param infoEvents
    */

    // ----------- << method.annotations@AAAAAAF3cmf6Vv1WDo0= >>
    // ----------- >>
    public void setInfoEvento(String infoEvents) {
    // ----------- << method.body@AAAAAAF3cmf6Vv1WDo0= >>
    // ----------- >>
    }
    /**
    * @param nota
    */

    // ----------- << method.annotations@AAAAAAF3ZISgan8FPOw= >>
    // ----------- >>
    public void setPleaseNote(String nota) {
    // ----------- << method.body@AAAAAAF3ZISgan8FPOw= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3YyVBev/bYtw= >>
// ----------- >>
}