/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package ModelUMLTicketMaster;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3ZIjsOX8zaZk= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3ZIjsOX8zaZk= >>
// ----------- >>
public class FasciaDiPrezzo {
    // ----------- << attribute.annotations@AAAAAAF3ZIndb39gzw0= >>
    // ----------- >>
    private String tipoBiglietto;

    // ----------- << attribute.annotations@AAAAAAF3ZInrCH9mq8s= >>
    // ----------- >>
    private String valuta;

    // ----------- << attribute.annotations@AAAAAAF3ZIn5q39sjHg= >>
    // ----------- >>
    private double prezzoMinimo;

    // ----------- << attribute.annotations@AAAAAAF3ZIoGZX9yA24= >>
    // ----------- >>
    private double prezzoMassimo;

    private String getTipoBiglietto() {
        return tipoBiglietto;
    }

    private String getValuta() {
        return valuta;
    }

    private double getPrezzoMinimo() {
        return prezzoMinimo;
    }

    private double getPrezzoMassimo() {
        return prezzoMassimo;
    }

    private void setTipoBiglietto(String tipoBiglietto) {
        this.tipoBiglietto = tipoBiglietto;
    }

    private void setValuta(String valuta) {
        this.valuta = valuta;
    }

    private void setPrezzoMinimo(double prezzoMinimo) {
        this.prezzoMinimo = prezzoMinimo;
    }

    private void setPrezzoMassimo(double prezzoMassimo) {
        this.prezzoMassimo = prezzoMassimo;
    }

    // ----------- << method.annotations@AAAAAAF3ZIt6y3+BIj4= >>
    // ----------- >>
    public FasciaDiPrezzo() {
    // ----------- << method.body@AAAAAAF3ZIt6y3+BIj4= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZIuMd3+HkbE= >>
    // ----------- >>
    public String getTipoBiglietto() {
    // ----------- << method.body@AAAAAAF3ZIuMd3+HkbE= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZIuaEH+NPuI= >>
    // ----------- >>
    public String getValuta() {
    // ----------- << method.body@AAAAAAF3ZIuaEH+NPuI= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZIunQH+TF2g= >>
    // ----------- >>
    public double getPrezzoMinimo() {
    // ----------- << method.body@AAAAAAF3ZIunQH+TF2g= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZIu6pH+ZsSE= >>
    // ----------- >>
    public double getPrezzoMassimo() {
    // ----------- << method.body@AAAAAAF3ZIu6pH+ZsSE= >>
    // ----------- >>
    }
    /**
    * @param tycketType
    */

    // ----------- << method.annotations@AAAAAAF3ZIvJ73+ft20= >>
    // ----------- >>
    public void setTipoBiglietto(String tycketType) {
    // ----------- << method.body@AAAAAAF3ZIvJ73+ft20= >>
    // ----------- >>
    }
    /**
    * @param currency
    */

    // ----------- << method.annotations@AAAAAAF3ZIvgVX+lH8M= >>
    // ----------- >>
    public void setValuta(String currency) {
    // ----------- << method.body@AAAAAAF3ZIvgVX+lH8M= >>
    // ----------- >>
    }
    /**
    * @param min
    */

    // ----------- << method.annotations@AAAAAAF3ZIvxBX+rVl0= >>
    // ----------- >>
    public void setPrezzoMinimo(double min) {
    // ----------- << method.body@AAAAAAF3ZIvxBX+rVl0= >>
    // ----------- >>
    }
    /**
    * @param max
    */

    // ----------- << method.annotations@AAAAAAF3ZIwLVH+xnsc= >>
    // ----------- >>
    public void setPrezzoMassimo(double max) {
    // ----------- << method.body@AAAAAAF3ZIwLVH+xnsc= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3ZIjsOX8zaZk= >>
// ----------- >>
}