/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package ModelUMLTicketMaster;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3ZJKIhH/t6oM= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3ZJKIhH/t6oM= >>
// ----------- >>
public class MappaPostoUtente {
    // ----------- << attribute.annotations@AAAAAAF3ZJLevYAZMyU= >>
    // ----------- >>
    private String mappaPosto;

    private String getMappaPosto() {
        return mappaPosto;
    }

    private void setMappaPosto(String mappaPosto) {
        this.mappaPosto = mappaPosto;
    }

    // ----------- << method.annotations@AAAAAAF3ZJNQNIAim4o= >>
    // ----------- >>
    public MappaPostoUtente() {
    // ----------- << method.body@AAAAAAF3ZJNQNIAim4o= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZJNfnYAoM4g= >>
    // ----------- >>
    public String getMappaPosto() {
    // ----------- << method.body@AAAAAAF3ZJNfnYAoM4g= >>
    // ----------- >>
    }
    /**
    * @param posto
    */

    // ----------- << method.annotations@AAAAAAF3ZJP534AyoQA= >>
    // ----------- >>
    public void setMappaPosto(String posto) {
    // ----------- << method.body@AAAAAAF3ZJP534AyoQA= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3ZJKIhH/t6oM= >>
// ----------- >>
}