/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package ModelUMLTicketMaster;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3ZJaz+IBJCGM= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3ZJaz+IBJCGM= >>
// ----------- >>
public class MassimoBiglietti {
    // ----------- << attribute.annotations@AAAAAAF3ZJcu6YB3zM0= >>
    // ----------- >>
    private String info;

    private String getInfo() {
        return info;
    }

    private void setInfo(String info) {
        this.info = info;
    }

    // ----------- << method.annotations@AAAAAAF3ZJd8mYB/+mQ= >>
    // ----------- >>
    public MassimoBiglietti() {
    // ----------- << method.body@AAAAAAF3ZJd8mYB/+mQ= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZJeMK4CFThM= >>
    // ----------- >>
    public String getInfo() {
    // ----------- << method.body@AAAAAAF3ZJeMK4CFThM= >>
    // ----------- >>
    }
    /**
    * @param informazioni
    */

    // ----------- << method.annotations@AAAAAAF3ZJeeL4CLA2U= >>
    // ----------- >>
    public void setInfo(String informazioni) {
    // ----------- << method.body@AAAAAAF3ZJeeL4CLA2U= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3ZJaz+IBJCGM= >>
// ----------- >>
}