/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package EmbeddedPackage;

import java.util.*;
import java.time.*;


import PackageClassificazione.Classificazione;
// ----------- << imports@AAAAAAF3amjJJ0QKU/Q= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3amjJJ0QKU/Q= >>
// ----------- >>
public class Attrazioni {
    // ----------- << attribute.annotations@AAAAAAF3ampdC0Q4P5Y= >>
    // ----------- >>
    private String nomeAttrazione;

    // ----------- << attribute.annotations@AAAAAAF3ampoAkQ+9JI= >>
    // ----------- >>
    private String tipoAttrazione;

    // ----------- << attribute.annotations@AAAAAAF3ampyaUREbz0= >>
    // ----------- >>
    private String idAttrazione;

    // ----------- << attribute.annotations@AAAAAAF3amqEN0RKO3s= >>
    // ----------- >>
    private String urlAttrazione;

    // ----------- << attribute.annotations@AAAAAAF3amws70Ra78I= >>
    // ----------- >>
    private Classificazione classificazioneAttrazione;

    // ----------- << attribute.annotations@AAAAAAF3antp/ESIP9w= >>
    // ----------- >>
    private EventiInArrivo eventiIncoming;

    // ----------- << attribute.annotations@AAAAAAF3crxBCxpEzA4= >>
    // ----------- >>
    private Set<Classificazione>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF3cr9ddzCyLlQ= >>
    // ----------- >>
    private EventiInArrivo ;

    private String getNomeAttrazione() {
        return nomeAttrazione;
    }

    private String getTipoAttrazione() {
        return tipoAttrazione;
    }

    private String getIdAttrazione() {
        return idAttrazione;
    }

    private String getUrlAttrazione() {
        return urlAttrazione;
    }

    private Classificazione getClassificazioneAttrazione() {
        return classificazioneAttrazione;
    }

    private EventiInArrivo getEventiIncoming() {
        return eventiIncoming;
    }

    public Set<Classificazione> get() {
        return ;
    }

    public EventiInArrivo get() {
        return ;
    }

    private void setNomeAttrazione(String nomeAttrazione) {
        this.nomeAttrazione = nomeAttrazione;
    }

    private void setTipoAttrazione(String tipoAttrazione) {
        this.tipoAttrazione = tipoAttrazione;
    }

    private void setIdAttrazione(String idAttrazione) {
        this.idAttrazione = idAttrazione;
    }

    private void setUrlAttrazione(String urlAttrazione) {
        this.urlAttrazione = urlAttrazione;
    }

    private void setClassificazioneAttrazione(Classificazione classificazioneAttrazione) {
        this.classificazioneAttrazione = classificazioneAttrazione;
    }

    private void setEventiIncoming(EventiInArrivo eventiIncoming) {
        this.eventiIncoming = eventiIncoming;
    }

    public void set(EventiInArrivo ) {
        this. = ;
    }

    public void link(Classificazione _) {
        if (_ != null) {
            get().add(_);
        }
    }

    public void link(EventiInArrivo _) {
        set(_);
    }

    public void unlink(Classificazione _) {
        if (_ != null) {
            get().remove(_);
        }
    }

    public void unlink(Iterator<Classificazione> it) {
        it.remove();
    }

    public void unlink() {
        set(null);
    }

    // ----------- << method.annotations@AAAAAAF3apmneUU1dYY= >>
    // ----------- >>
    public Attrazioni() {
    // ----------- << method.body@AAAAAAF3apmneUU1dYY= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3apofGkU8kmM= >>
    // ----------- >>
    public String getNomeAttrazione() {
    // ----------- << method.body@AAAAAAF3apofGkU8kmM= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3appXhEVJEA4= >>
    // ----------- >>
    public String getTipoAttrazione() {
    // ----------- << method.body@AAAAAAF3appXhEVJEA4= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3appouEVPPzc= >>
    // ----------- >>
    public String getIdAttrazione() {
    // ----------- << method.body@AAAAAAF3appouEVPPzc= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3app3NEVVX3c= >>
    // ----------- >>
    public String getUrlAttrazione() {
    // ----------- << method.body@AAAAAAF3app3NEVVX3c= >>
    // ----------- >>
    }
    /**
    * @param attractionNames
    */

    // ----------- << method.annotations@AAAAAAF3apqCQkVbNt0= >>
    // ----------- >>
    public void setNomeAttrazione(String attractionNames) {
    // ----------- << method.body@AAAAAAF3apqCQkVbNt0= >>
    // ----------- >>
    }
    /**
    * @param attractionTypes
    */

    // ----------- << method.annotations@AAAAAAF3apqNQkVhgCY= >>
    // ----------- >>
    public void setTipoAttrazione(String attractionTypes) {
    // ----------- << method.body@AAAAAAF3apqNQkVhgCY= >>
    // ----------- >>
    }
    /**
    * @param attractionIds
    */

    // ----------- << method.annotations@AAAAAAF3apqfeUVnBnw= >>
    // ----------- >>
    public void setIdAttrazione(String attractionIds) {
    // ----------- << method.body@AAAAAAF3apqfeUVnBnw= >>
    // ----------- >>
    }
    /**
    * @param attractionUrls
    */

    // ----------- << method.annotations@AAAAAAF3apqqd0VtGPI= >>
    // ----------- >>
    public void setUrlAttrazione(String attractionUrls) {
    // ----------- << method.body@AAAAAAF3apqqd0VtGPI= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3amjJJ0QKU/Q= >>
// ----------- >>
}