/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package EmbeddedPackage;

import java.util.*;
import java.time.*;


import Eventi;
import PackageLuoghi.Luoghi;
// ----------- << imports@AAAAAAF3amFbV0Pg5tI= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3amFbV0Pg5tI= >>
// ----------- >>
public class Embedded {
    // ----------- << attribute.annotations@AAAAAAF3apd73UUe/Uw= >>
    // ----------- >>
    private Luogo places;

    // ----------- << attribute.annotations@AAAAAAF3apeK+0UkNZs= >>
    // ----------- >>
    private Attrazioni attractions;

    // ----------- << attribute.annotations@AAAAAAF3dC6y4l/1PBw= >>
    // ----------- >>
    private Eventi ;

    // ----------- << attribute.annotations@AAAAAAF3csjdkkT0PBs= >>
    // ----------- >>
    private Set<Luoghi>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF3csyzAWMBEDA= >>
    // ----------- >>
    private Set<Attrazioni>  = new HashSet<>();

    private Luogo getPlaces() {
        return places;
    }

    private Attrazioni getAttractions() {
        return attractions;
    }

    public Eventi get() {
        return ;
    }

    public Set<Luoghi> get() {
        return ;
    }

    public Set<Attrazioni> get() {
        return ;
    }

    private void setPlaces(Luogo places) {
        this.places = places;
    }

    private void setAttractions(Attrazioni attractions) {
        this.attractions = attractions;
    }

    public void set(Eventi ) {
        this. = ;
    }

    public void link(Eventi _) {
        set(_);
    }

    public void link(Luoghi _) {
        if (_ != null) {
            get().add(_);
        }
    }

    public void link(Attrazioni _) {
        if (_ != null) {
            get().add(_);
        }
    }

    public void unlink() {
        set(null);
    }

    public void unlink(Luoghi _) {
        if (_ != null) {
            get().remove(_);
        }
    }

    public void unlink(Iterator<Luoghi> it) {
        it.remove();
    }

    public void unlink(Attrazioni _) {
        if (_ != null) {
            get().remove(_);
        }
    }

    public void unlink(Iterator<Attrazioni> it) {
        it.remove();
    }

    // ----------- << method.annotations@AAAAAAF3aph72UUulHE= >>
    // ----------- >>
    public Embedded() {
    // ----------- << method.body@AAAAAAF3aph72UUulHE= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3amFbV0Pg5tI= >>
// ----------- >>
}