/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package EmbeddedPackage;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3ZRiiFoc++mY= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3ZRiiFoc++mY= >>
// ----------- >>
public class EventiInArrivo {
    // ----------- << attribute.annotations@AAAAAAF3ZRjsyYdqGCo= >>
    // ----------- >>
    private int totaleEventiInArrivo;

    // ----------- << attribute.annotations@AAAAAAF3anDwsERjp1w= >>
    // ----------- >>
    private int mfx-at;

    // ----------- << attribute.annotations@AAAAAAF3anD61URptm8= >>
    // ----------- >>
    private int mfx-nl;

    // ----------- << attribute.annotations@AAAAAAF3anEG40RvC/k= >>
    // ----------- >>
    private int mfx-de;

    // ----------- << attribute.annotations@AAAAAAF3ZRkkfIdw6QQ= >>
    // ----------- >>
    private int ticketmaster;

    // ----------- << attribute.annotations@AAAAAAF3anIHUER6ghU= >>
    // ----------- >>
    private int mfx-se;

    private int getTotaleEventiInArrivo() {
        return totaleEventiInArrivo;
    }

    private int getMfx-at() {
        return mfx-at;
    }

    private int getMfx-nl() {
        return mfx-nl;
    }

    private int getMfx-de() {
        return mfx-de;
    }

    private int getTicketmaster() {
        return ticketmaster;
    }

    private int getMfx-se() {
        return mfx-se;
    }

    private void setTotaleEventiInArrivo(int totaleEventiInArrivo) {
        this.totaleEventiInArrivo = totaleEventiInArrivo;
    }

    private void setMfx-at(int mfx-at) {
        this.mfx-at = mfx-at;
    }

    private void setMfx-nl(int mfx-nl) {
        this.mfx-nl = mfx-nl;
    }

    private void setMfx-de(int mfx-de) {
        this.mfx-de = mfx-de;
    }

    private void setTicketmaster(int ticketmaster) {
        this.ticketmaster = ticketmaster;
    }

    private void setMfx-se(int mfx-se) {
        this.mfx-se = mfx-se;
    }

    // ----------- << method.annotations@AAAAAAF3ZRqCGod9Qy4= >>
    // ----------- >>
    public EventiInArrivo() {
    // ----------- << method.body@AAAAAAF3ZRqCGod9Qy4= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZRqVd4eDedE= >>
    // ----------- >>
    public int getTotaleEventiInArrivo() {
    // ----------- << method.body@AAAAAAF3ZRqVd4eDedE= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3anxenEStDPM= >>
    // ----------- >>
    public int getMfxAt() {
    // ----------- << method.body@AAAAAAF3anxenEStDPM= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3anxyHESzeWs= >>
    // ----------- >>
    public int getMfxNl() {
    // ----------- << method.body@AAAAAAF3anxyHESzeWs= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3anx83kS5uyE= >>
    // ----------- >>
    public int getMfxDe() {
    // ----------- << method.body@AAAAAAF3anx83kS5uyE= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZRqpQ4eJ8VE= >>
    // ----------- >>
    public int getTicketmaster() {
    // ----------- << method.body@AAAAAAF3ZRqpQ4eJ8VE= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3anyHXkS/PfY= >>
    // ----------- >>
    public int getMfxSe() {
    // ----------- << method.body@AAAAAAF3anyHXkS/PfY= >>
    // ----------- >>
    }
    /**
    * @param totaleEventi
    */

    // ----------- << method.annotations@AAAAAAF3ZRq9DIePgk0= >>
    // ----------- >>
    public void setTotaleEventiInArrivo(int totaleEventi) {
    // ----------- << method.body@AAAAAAF3ZRq9DIePgk0= >>
    // ----------- >>
    }
    /**
    * @param at
    */

    // ----------- << method.annotations@AAAAAAF3anyUu0TFRb0= >>
    // ----------- >>
    public void setMfxAt(int at) {
    // ----------- << method.body@AAAAAAF3anyUu0TFRb0= >>
    // ----------- >>
    }
    /**
    * @param nl
    */

    // ----------- << method.annotations@AAAAAAF3anykwETLk3I= >>
    // ----------- >>
    public void setMfxNl(int nl) {
    // ----------- << method.body@AAAAAAF3anykwETLk3I= >>
    // ----------- >>
    }
    /**
    * @param de
    */

    // ----------- << method.annotations@AAAAAAF3anyxfkTR1+I= >>
    // ----------- >>
    public void setMfxDe(int de) {
    // ----------- << method.body@AAAAAAF3anyxfkTR1+I= >>
    // ----------- >>
    }
    /**
    * @param totaleTicketmaster
    */

    // ----------- << method.annotations@AAAAAAF3ZRrOPoeV6uk= >>
    // ----------- >>
    public void setTicketmaster(int totaleTicketmaster) {
    // ----------- << method.body@AAAAAAF3ZRrOPoeV6uk= >>
    // ----------- >>
    }
    /**
    * @param se
    */

    // ----------- << method.annotations@AAAAAAF3anzALUTXGY8= >>
    // ----------- >>
    public void setMfxSe(int se) {
    // ----------- << method.body@AAAAAAF3anzALUTXGY8= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3ZRiiFoc++mY= >>
// ----------- >>
}