/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageDataEvento;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3Y7FpOngygSs= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3Y7FpOngygSs= >>
// ----------- >>
public class DataEvento {
    // ----------- << attribute.annotations@AAAAAAF3Y+xdwHm99Ac= >>
    // ----------- >>
    private String timezone;

    // ----------- << attribute.annotations@AAAAAAF3Y/CFbHnvifQ= >>
    // ----------- >>
    private Data data_evento;

    // ----------- << attribute.annotations@AAAAAAF3Y/NdfnpKO34= >>
    // ----------- >>
    private Situazione status;

    // ----------- << attribute.annotations@AAAAAAF3clADtL8uOYI= >>
    // ----------- >>
    private Data ;

    // ----------- << attribute.annotations@AAAAAAF3clG+jMFBfhI= >>
    // ----------- >>
    private Situazione ;

    private String getTimezone() {
        return timezone;
    }

    private Data getData_evento() {
        return data_evento;
    }

    private Situazione getStatus() {
        return status;
    }

    public Data get() {
        return ;
    }

    public Situazione get() {
        return ;
    }

    private void setTimezone(String timezone) {
        this.timezone = timezone;
    }

    private void setData_evento(Data data_evento) {
        this.data_evento = data_evento;
    }

    private void setStatus(Situazione status) {
        this.status = status;
    }

    public void set(Data ) {
        this. = ;
    }

    public void set(Situazione ) {
        this. = ;
    }

    public void link(Data _) {
        set(_);
    }

    public void link(Situazione _) {
        set(_);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }

    // ----------- << method.annotations@AAAAAAF3Y+3zuHnMR/Y= >>
    // ----------- >>
    public DataEvento() {
    // ----------- << method.body@AAAAAAF3Y+3zuHnMR/Y= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3Y+4sv3nTEeE= >>
    // ----------- >>
    public String getTimezone() {
    // ----------- << method.body@AAAAAAF3Y+4sv3nTEeE= >>
    // ----------- >>
    }
    /**
    * @param nuovaTimezone
    */

    // ----------- << method.annotations@AAAAAAF3Y+5duXnacjM= >>
    // ----------- >>
    public void setTimezone(String nuovaTimezone) {
    // ----------- << method.body@AAAAAAF3Y+5duXnacjM= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3Y7FpOngygSs= >>
// ----------- >>
}