/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageDataEvento;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3Y7TqAHhewpM= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3Y7TqAHhewpM= >>
// ----------- >>
public class Data {
    // ----------- << attribute.annotations@AAAAAAF3Y7WoeXiJHcQ= >>
    // ----------- >>
    private LocalDate dataLocale;

    // ----------- << attribute.annotations@AAAAAAF3Y7XF3HiPSqM= >>
    // ----------- >>
    private LocalDate oraLocale;

    // ----------- << attribute.annotations@AAAAAAF3Y7a6hXiZLsI= >>
    // ----------- >>
    private LocalDate dataOraLocale;

    // ----------- << attribute.annotations@AAAAAAF3Y+eS/nmOv0E= >>
    // ----------- >>
    private boolean tempoTBA;

    private LocalDate getDataLocale() {
        return dataLocale;
    }

    private LocalDate getOraLocale() {
        return oraLocale;
    }

    private LocalDate getDataOraLocale() {
        return dataOraLocale;
    }

    private boolean isTempoTBA() {
        return tempoTBA;
    }

    private void setDataLocale(LocalDate dataLocale) {
        this.dataLocale = dataLocale;
    }

    private void setOraLocale(LocalDate oraLocale) {
        this.oraLocale = oraLocale;
    }

    private void setDataOraLocale(LocalDate dataOraLocale) {
        this.dataOraLocale = dataOraLocale;
    }

    private void setTempoTBA(boolean tempoTBA) {
        this.tempoTBA = tempoTBA;
    }

    // ----------- << method.annotations@AAAAAAF3Y7yPXnj8Ey0= >>
    // ----------- >>
    public Data() {
    // ----------- << method.body@AAAAAAF3Y7yPXnj8Ey0= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3Y7eJD3iial0= >>
    // ----------- >>
    public LocalDate getDataLocale() {
    // ----------- << method.body@AAAAAAF3Y7eJD3iial0= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3Y7egKnioFU4= >>
    // ----------- >>
    public LocalDate getOraLocale() {
    // ----------- << method.body@AAAAAAF3Y7egKnioFU4= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3Y7e5RXivCEM= >>
    // ----------- >>
    public LocalDate getDataOraLocale() {
    // ----------- << method.body@AAAAAAF3Y7e5RXivCEM= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3Y+hO2HmWwhY= >>
    // ----------- >>
    public boolean getTempoTBA() {
    // ----------- << method.body@AAAAAAF3Y+hO2HmWwhY= >>
    // ----------- >>
    }
    /**
    * @param dataLoc
    */

    // ----------- << method.annotations@AAAAAAF3Y7fH43i1bf0= >>
    // ----------- >>
    public void setDataLocale(LocalDate dataLoc) {
    // ----------- << method.body@AAAAAAF3Y7fH43i1bf0= >>
    // ----------- >>
    }
    /**
    * @param oraLoc
    */

    // ----------- << method.annotations@AAAAAAF3Y7fY9Xi7qAk= >>
    // ----------- >>
    public void setOraLocale(LocalDate oraLoc) {
    // ----------- << method.body@AAAAAAF3Y7fY9Xi7qAk= >>
    // ----------- >>
    }
    /**
    * @param dataOraLoc
    */

    // ----------- << method.annotations@AAAAAAF3Y7fp6XjBpWU= >>
    // ----------- >>
    public void setDataOraLocale(LocalDate dataOraLoc) {
    // ----------- << method.body@AAAAAAF3Y7fp6XjBpWU= >>
    // ----------- >>
    }
    /**
    * @param timeTBA
    */

    // ----------- << method.annotations@AAAAAAF3Y+l5k3mmXzo= >>
    // ----------- >>
    public void setTempoTBA(boolean timeTBA) {
    // ----------- << method.body@AAAAAAF3Y+l5k3mmXzo= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3Y7TqAHhewpM= >>
// ----------- >>
}