/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageDataEvento;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3Y/GluXn46Eg= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3Y/GluXn46Eg= >>
// ----------- >>
public class Situazione {
    // ----------- << attribute.annotations@AAAAAAF3Y/IKWnok6oE= >>
    // ----------- >>
    private String codice;

    private String getCodice() {
        return codice;
    }

    private void setCodice(String codice) {
        this.codice = codice;
    }

    // ----------- << method.annotations@AAAAAAF3Y/JWj3osAog= >>
    // ----------- >>
    public Situazione() {
    // ----------- << method.body@AAAAAAF3Y/JWj3osAog= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3Y/JjQHoyVAc= >>
    // ----------- >>
    public String getCodice() {
    // ----------- << method.body@AAAAAAF3Y/JjQHoyVAc= >>
    // ----------- >>
    }
    /**
    * @param code
    */

    // ----------- << method.annotations@AAAAAAF3Y/J7Rno4P0I= >>
    // ----------- >>
    public void setCodice(String code) {
    // ----------- << method.body@AAAAAAF3Y/J7Rno4P0I= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3Y/GluXn46Eg= >>
// ----------- >>
}