/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageLinks;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3ZKyqB4ClzGs= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3ZKyqB4ClzGs= >>
// ----------- >>
public class Link {
    // ----------- << attribute.annotations@AAAAAAF3ZMh2jYHMnm0= >>
    // ----------- >>
    private LinkEvento linkEvento;

    // ----------- << attribute.annotations@AAAAAAF3ZMiGu4HS/Gw= >>
    // ----------- >>
    private LinkAttrazioni linkAttrazioni;

    // ----------- << attribute.annotations@AAAAAAF3ZMiVyYHYRbQ= >>
    // ----------- >>
    private LinkSedi linkSedi;

    // ----------- << attribute.annotations@AAAAAAF3coBv0SLUZi8= >>
    // ----------- >>
    private LinkEvento ;

    // ----------- << attribute.annotations@AAAAAAF3coQAujS7bvo= >>
    // ----------- >>
    private Set<LinkAttrazioni>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF3coaQ80QUHjg= >>
    // ----------- >>
    private Set<LinkSedi>  = new HashSet<>();

    private LinkEvento getLinkEvento() {
        return linkEvento;
    }

    private LinkAttrazioni getLinkAttrazioni() {
        return linkAttrazioni;
    }

    private LinkSedi getLinkSedi() {
        return linkSedi;
    }

    public LinkEvento get() {
        return ;
    }

    public Set<LinkAttrazioni> get() {
        return ;
    }

    public Set<LinkSedi> get() {
        return ;
    }

    private void setLinkEvento(LinkEvento linkEvento) {
        this.linkEvento = linkEvento;
    }

    private void setLinkAttrazioni(LinkAttrazioni linkAttrazioni) {
        this.linkAttrazioni = linkAttrazioni;
    }

    private void setLinkSedi(LinkSedi linkSedi) {
        this.linkSedi = linkSedi;
    }

    public void set(LinkEvento ) {
        this. = ;
    }

    public void link(LinkEvento _) {
        set(_);
    }

    public void link(LinkAttrazioni _) {
        if (_ != null) {
            get().add(_);
        }
    }

    public void link(LinkSedi _) {
        if (_ != null) {
            get().add(_);
        }
    }

    public void unlink() {
        set(null);
    }

    public void unlink(LinkAttrazioni _) {
        if (_ != null) {
            get().remove(_);
        }
    }

    public void unlink(Iterator<LinkAttrazioni> it) {
        it.remove();
    }

    public void unlink(LinkSedi _) {
        if (_ != null) {
            get().remove(_);
        }
    }

    public void unlink(Iterator<LinkSedi> it) {
        it.remove();
    }

    // ----------- << method.annotations@AAAAAAF3ZMimoYHehRM= >>
    // ----------- >>
    public Link() {
    // ----------- << method.body@AAAAAAF3ZMimoYHehRM= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3ZKyqB4ClzGs= >>
// ----------- >>
}