/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageLinks;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3ZLkrpYEjxjI= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3ZLkrpYEjxjI= >>
// ----------- >>
public class LinkAttrazioni {
    // ----------- << attribute.annotations@AAAAAAF3ZLnBD4FQDjc= >>
    // ----------- >>
    private String linkAttrazione;

    private String getLinkAttrazione() {
        return linkAttrazione;
    }

    private void setLinkAttrazione(String linkAttrazione) {
        this.linkAttrazione = linkAttrazione;
    }

    // ----------- << method.annotations@AAAAAAF3ZLt8PYFbHzg= >>
    // ----------- >>
    public LinkAttrazioni() {
    // ----------- << method.body@AAAAAAF3ZLt8PYFbHzg= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZLuTqoFhKqY= >>
    // ----------- >>
    public String getLinkAttrazione() {
    // ----------- << method.body@AAAAAAF3ZLuTqoFhKqY= >>
    // ----------- >>
    }
    /**
    * @param hrefAttrazione
    */

    // ----------- << method.annotations@AAAAAAF3ZLumOYFnsfM= >>
    // ----------- >>
    public void setLinkAttrazione(String hrefAttrazione) {
    // ----------- << method.body@AAAAAAF3ZLumOYFnsfM= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3ZLkrpYEjxjI= >>
// ----------- >>
}