/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageLinks;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3ZLZlXIDR8ls= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3ZLZlXIDR8ls= >>
// ----------- >>
public class LinkEvento {
    // ----------- << attribute.annotations@AAAAAAF3ZLbgcYD+eVg= >>
    // ----------- >>
    private String linkEventoCorrente;

    private String getLinkEventoCorrente() {
        return linkEventoCorrente;
    }

    private void setLinkEventoCorrente(String linkEventoCorrente) {
        this.linkEventoCorrente = linkEventoCorrente;
    }

    // ----------- << method.annotations@AAAAAAF3ZLeSuIEFLb4= >>
    // ----------- >>
    public LinkEvento() {
    // ----------- << method.body@AAAAAAF3ZLeSuIEFLb4= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZLekZ4ELT5s= >>
    // ----------- >>
    public String getLinkEvento() {
    // ----------- << method.body@AAAAAAF3ZLekZ4ELT5s= >>
    // ----------- >>
    }
    /**
    * @param href
    */

    // ----------- << method.annotations@AAAAAAF3ZLe47YERrSE= >>
    // ----------- >>
    public void setLinkEvento(String href) {
    // ----------- << method.body@AAAAAAF3ZLe47YERrSE= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3ZLZlXIDR8ls= >>
// ----------- >>
}