/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageLinks;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3ZMPjs4F5BeQ= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3ZMPjs4F5BeQ= >>
// ----------- >>
public class LinkSedi {
    // ----------- << attribute.annotations@AAAAAAF3ZMSZkIGmPEU= >>
    // ----------- >>
    private String linkSedi;

    private String getLinkSedi() {
        return linkSedi;
    }

    private void setLinkSedi(String linkSedi) {
        this.linkSedi = linkSedi;
    }

    // ----------- << method.annotations@AAAAAAF3ZMT3T4GuxS8= >>
    // ----------- >>
    public LinkSedi() {
    // ----------- << method.body@AAAAAAF3ZMT3T4GuxS8= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZMUM84G0NcU= >>
    // ----------- >>
    public String getLinkSedi() {
    // ----------- << method.body@AAAAAAF3ZMUM84G0NcU= >>
    // ----------- >>
    }
    /**
    * @param hrefSedi
    */

    // ----------- << method.annotations@AAAAAAF3ZMUgsoG6sRY= >>
    // ----------- >>
    public void setLinkSedi(String hrefSedi) {
    // ----------- << method.body@AAAAAAF3ZMUgsoG6sRY= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3ZMPjs4F5BeQ= >>
// ----------- >>
}