/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageLuoghi;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3ZR3m9oe7Kpc= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3ZR3m9oe7Kpc= >>
// ----------- >>
public class Ada {
    // ----------- << attribute.annotations@AAAAAAF3ZR5l+4fmu3A= >>
    // ----------- >>
    private String adaPhones;

    // ----------- << attribute.annotations@AAAAAAF3ZR5534fsVGs= >>
    // ----------- >>
    private String adaCustomCopy;

    // ----------- << attribute.annotations@AAAAAAF3ZR6Q/ofyQ88= >>
    // ----------- >>
    private String adaHours;

    private String getAdaPhones() {
        return adaPhones;
    }

    private String getAdaCustomCopy() {
        return adaCustomCopy;
    }

    private String getAdaHours() {
        return adaHours;
    }

    private void setAdaPhones(String adaPhones) {
        this.adaPhones = adaPhones;
    }

    private void setAdaCustomCopy(String adaCustomCopy) {
        this.adaCustomCopy = adaCustomCopy;
    }

    private void setAdaHours(String adaHours) {
        this.adaHours = adaHours;
    }

    // ----------- << method.annotations@AAAAAAF3ZR+9fogAe74= >>
    // ----------- >>
    public Ada() {
    // ----------- << method.body@AAAAAAF3ZR+9fogAe74= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZR/TvogGGMo= >>
    // ----------- >>
    public String getAdaPhones() {
    // ----------- << method.body@AAAAAAF3ZR/TvogGGMo= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZR/p/YgMgCc= >>
    // ----------- >>
    public String getAdaCustomCopy() {
    // ----------- << method.body@AAAAAAF3ZR/p/YgMgCc= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZR//NIgSskk= >>
    // ----------- >>
    public String getAdaHours() {
    // ----------- << method.body@AAAAAAF3ZR//NIgSskk= >>
    // ----------- >>
    }
    /**
    * @param adaTelephone
    */

    // ----------- << method.annotations@AAAAAAF3ZSATN4gY6d8= >>
    // ----------- >>
    public void setAdaPhones(String adaTelephone) {
    // ----------- << method.body@AAAAAAF3ZSATN4gY6d8= >>
    // ----------- >>
    }
    /**
    * @param customCopy
    */

    // ----------- << method.annotations@AAAAAAF3ZSAsK4geASI= >>
    // ----------- >>
    public void setAdaCustomCopy(String customCopy) {
    // ----------- << method.body@AAAAAAF3ZSAsK4geASI= >>
    // ----------- >>
    }
    /**
    * @param newAdaHours
    */

    // ----------- << method.annotations@AAAAAAF3ZSBAVYgk05M= >>
    // ----------- >>
    public void setAdaHours(String newAdaHours) {
    // ----------- << method.body@AAAAAAF3ZSBAVYgk05M= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3ZR3m9oe7Kpc= >>
// ----------- >>
}