/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageLuoghi;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3ZQyhCYYlZhE= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3ZQyhCYYlZhE= >>
// ----------- >>
public class BoxOfficeInfo {
    // ----------- << attribute.annotations@AAAAAAF3ZQ2UQIZT4z0= >>
    // ----------- >>
    private String phoneNumberDetail;

    // ----------- << attribute.annotations@AAAAAAF3ZQ3Ax4ZZrtE= >>
    // ----------- >>
    private String openHoursDetail;

    // ----------- << attribute.annotations@AAAAAAF3ZQ5/jIZj5dY= >>
    // ----------- >>
    private String willCallDetail;

    private String getPhoneNumberDetail() {
        return phoneNumberDetail;
    }

    private String getOpenHoursDetail() {
        return openHoursDetail;
    }

    private String getWillCallDetail() {
        return willCallDetail;
    }

    private void setPhoneNumberDetail(String phoneNumberDetail) {
        this.phoneNumberDetail = phoneNumberDetail;
    }

    private void setOpenHoursDetail(String openHoursDetail) {
        this.openHoursDetail = openHoursDetail;
    }

    private void setWillCallDetail(String willCallDetail) {
        this.willCallDetail = willCallDetail;
    }

    // ----------- << method.annotations@AAAAAAF3ZQ7iRoZrO/A= >>
    // ----------- >>
    public BoxOfficeInfo() {
    // ----------- << method.body@AAAAAAF3ZQ7iRoZrO/A= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZQ7yjYZxg4A= >>
    // ----------- >>
    public String getPhoneNumberDetail() {
    // ----------- << method.body@AAAAAAF3ZQ7yjYZxg4A= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZQ8J74Z3teo= >>
    // ----------- >>
    public String getOpenHoursDetail() {
    // ----------- << method.body@AAAAAAF3ZQ8J74Z3teo= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZQ8YEIZ9JE4= >>
    // ----------- >>
    public String getWillCallDetail() {
    // ----------- << method.body@AAAAAAF3ZQ8YEIZ9JE4= >>
    // ----------- >>
    }
    /**
    * @param phone
    */

    // ----------- << method.annotations@AAAAAAF3ZQ8olYaDPWs= >>
    // ----------- >>
    public void setPhoneNumberDetail(String phone) {
    // ----------- << method.body@AAAAAAF3ZQ8olYaDPWs= >>
    // ----------- >>
    }
    /**
    * @param openHours
    */

    // ----------- << method.annotations@AAAAAAF3ZQ89RoaJbig= >>
    // ----------- >>
    public void setOpenHoursDetail(String openHours) {
    // ----------- << method.body@AAAAAAF3ZQ89RoaJbig= >>
    // ----------- >>
    }
    /**
    * @param willCall
    */

    // ----------- << method.annotations@AAAAAAF3ZRENl4afTYM= >>
    // ----------- >>
    public void setWillCallDetail(String willCall) {
    // ----------- << method.body@AAAAAAF3ZRENl4afTYM= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3ZQyhCYYlZhE= >>
// ----------- >>
}