/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageLuoghi;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3ZOs98YMcWVs= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3ZOs98YMcWVs= >>
// ----------- >>
public class Citta {
    // ----------- << attribute.annotations@AAAAAAF3ZOuUooNIqlg= >>
    // ----------- >>
    private String nomeCitta;

    private String getNomeCitta() {
        return nomeCitta;
    }

    private void setNomeCitta(String nomeCitta) {
        this.nomeCitta = nomeCitta;
    }

    // ----------- << method.annotations@AAAAAAF3ZOvSkYNPvKo= >>
    // ----------- >>
    public Citta() {
    // ----------- << method.body@AAAAAAF3ZOvSkYNPvKo= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZOv7WYNWIr4= >>
    // ----------- >>
    public String getNomeCitta() {
    // ----------- << method.body@AAAAAAF3ZOv7WYNWIr4= >>
    // ----------- >>
    }
    /**
    * @param cityName
    */

    // ----------- << method.annotations@AAAAAAF3ZOwNcYNcx/8= >>
    // ----------- >>
    public void setNomeCitta(String cityName) {
    // ----------- << method.body@AAAAAAF3ZOwNcYNcx/8= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3ZOs98YMcWVs= >>
// ----------- >>
}