/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageLuoghi;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3ZQWNNoXGDGA= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3ZQWNNoXGDGA= >>
// ----------- >>
public class Dmas {
    // ----------- << attribute.annotations@AAAAAAF3ZQXro4X0eis= >>
    // ----------- >>
    private int dma;

    private int getDma() {
        return dma;
    }

    private void setDma(int dma) {
        this.dma = dma;
    }

    // ----------- << method.annotations@AAAAAAF3ZQhct4X84hU= >>
    // ----------- >>
    public Dmas() {
    // ----------- << method.body@AAAAAAF3ZQhct4X84hU= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZQh0HoYCodc= >>
    // ----------- >>
    public int getDmas() {
    // ----------- << method.body@AAAAAAF3ZQh0HoYCodc= >>
    // ----------- >>
    }
    /**
    * @param dmaNumber
    */

    // ----------- << method.annotations@AAAAAAF3ZQiN7oYIu3E= >>
    // ----------- >>
    public void setDmas(int dmaNumber) {
    // ----------- << method.body@AAAAAAF3ZQiN7oYIu3E= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3ZQWNNoXGDGA= >>
// ----------- >>
}