/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageLuoghi;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3ZPm38YRxlFs= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3ZPm38YRxlFs= >>
// ----------- >>
public class Indirizzo {
    // ----------- << attribute.annotations@AAAAAAF3ZPoWK4Sdxqc= >>
    // ----------- >>
    private String line1;

    private String getLine1() {
        return line1;
    }

    private void setLine1(String line1) {
        this.line1 = line1;
    }

    // ----------- << method.annotations@AAAAAAF3ZPqXVYSmuag= >>
    // ----------- >>
    public Indirizzo() {
    // ----------- << method.body@AAAAAAF3ZPqXVYSmuag= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZPqpWoSsnZo= >>
    // ----------- >>
    public String getIndirizzo() {
    // ----------- << method.body@AAAAAAF3ZPqpWoSsnZo= >>
    // ----------- >>
    }
    /**
    * @param address
    */

    // ----------- << method.annotations@AAAAAAF3ZPq8RoSy5O0= >>
    // ----------- >>
    public void setIndirizzo(String address) {
    // ----------- << method.body@AAAAAAF3ZPq8RoSy5O0= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3ZPm38YRxlFs= >>
// ----------- >>
}