/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageLuoghi;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3ZRVfJIbk84s= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3ZRVfJIbk84s= >>
// ----------- >>
public class InfoGeneriche {
    // ----------- << attribute.annotations@AAAAAAF3ZRXJ5ocQ4ug= >>
    // ----------- >>
    private String childRule;

    private String getChildRule() {
        return childRule;
    }

    private void setChildRule(String childRule) {
        this.childRule = childRule;
    }

    // ----------- << method.annotations@AAAAAAF3ZRYVw4cYor0= >>
    // ----------- >>
    public InfoGeneriche() {
    // ----------- << method.body@AAAAAAF3ZRYVw4cYor0= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZRYu44cedJA= >>
    // ----------- >>
    public String getChildRule() {
    // ----------- << method.body@AAAAAAF3ZRYu44cedJA= >>
    // ----------- >>
    }
    /**
    * @param rules
    */

    // ----------- << method.annotations@AAAAAAF3ZRZEZ4ck3Lw= >>
    // ----------- >>
    public void setChildRule(String rules) {
    // ----------- << method.body@AAAAAAF3ZRZEZ4ck3Lw= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3ZRVfJIbk84s= >>
// ----------- >>
}