/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageLuoghi;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3ZPuS6YTE9ps= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3ZPuS6YTE9ps= >>
// ----------- >>
public class Location {
    // ----------- << attribute.annotations@AAAAAAF3ZPxkI4T6j3M= >>
    // ----------- >>
    private String longitudine;

    // ----------- << attribute.annotations@AAAAAAF3ZPx3OIUA5m0= >>
    // ----------- >>
    private String latitudine;

    private String getLongitudine() {
        return longitudine;
    }

    private String getLatitudine() {
        return latitudine;
    }

    private void setLongitudine(String longitudine) {
        this.longitudine = longitudine;
    }

    private void setLatitudine(String latitudine) {
        this.latitudine = latitudine;
    }

    // ----------- << method.annotations@AAAAAAF3ZP4S8IULb6Y= >>
    // ----------- >>
    public Location() {
    // ----------- << method.body@AAAAAAF3ZP4S8IULb6Y= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZP4mVIURI5U= >>
    // ----------- >>
    public String getLongitudine() {
    // ----------- << method.body@AAAAAAF3ZP4mVIURI5U= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZP42JoUXI/c= >>
    // ----------- >>
    public String getLatitudine() {
    // ----------- << method.body@AAAAAAF3ZP42JoUXI/c= >>
    // ----------- >>
    }
    /**
    * @param longitude
    */

    // ----------- << method.annotations@AAAAAAF3ZP5G1oUdhqA= >>
    // ----------- >>
    public void setLongitudine(String longitude) {
    // ----------- << method.body@AAAAAAF3ZP5G1oUdhqA= >>
    // ----------- >>
    }
    /**
    * @param latitude
    */

    // ----------- << method.annotations@AAAAAAF3ZP5ZYoUjUjI= >>
    // ----------- >>
    public void setLatitudine(String latitude) {
    // ----------- << method.body@AAAAAAF3ZP5ZYoUjUjI= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3ZPuS6YTE9ps= >>
// ----------- >>
}