/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageLuoghi;

import java.util.*;
import java.time.*;


import EmbeddedPackage.EventiInArrivo;
// ----------- << imports@AAAAAAF3ZNGoM4IfvpY= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3ZNGoM4IfvpY= >>
// ----------- >>
public class Luoghi {
    // ----------- << attribute.annotations@AAAAAAF3ZNK5s4JNZog= >>
    // ----------- >>
    private String nomeLuogo;

    // ----------- << attribute.annotations@AAAAAAF3ZNLHPIJTkn4= >>
    // ----------- >>
    private String tipoLuogo;

    // ----------- << attribute.annotations@AAAAAAF3ZNLW+oJZzm8= >>
    // ----------- >>
    private String idLuogo;

    // ----------- << attribute.annotations@AAAAAAF3ZNSbAoJlwaA= >>
    // ----------- >>
    private String urlLuogo;

    // ----------- << attribute.annotations@AAAAAAF3ZNqBS4JzJ34= >>
    // ----------- >>
    private String codicePostale;

    // ----------- << attribute.annotations@AAAAAAF3ZNqRBoJ5xxA= >>
    // ----------- >>
    private String fusoOrario;

    // ----------- << attribute.annotations@AAAAAAF3ZO0NAINvXRQ= >>
    // ----------- >>
    private Citta citta;

    // ----------- << attribute.annotations@AAAAAAF3ZPHEB4PqkvQ= >>
    // ----------- >>
    private Stato stato;

    // ----------- << attribute.annotations@AAAAAAF3ZPj+qYRpvvk= >>
    // ----------- >>
    private Paese paese;

    // ----------- << attribute.annotations@AAAAAAF3ZPvJZoTu/Pg= >>
    // ----------- >>
    private Indirizzo indirizzo;

    // ----------- << attribute.annotations@AAAAAAF3ZP/xi4VBVGI= >>
    // ----------- >>
    private Location location;

    // ----------- << attribute.annotations@AAAAAAF3ZQQvvIW8kIo= >>
    // ----------- >>
    private Mercati mercato;

    // ----------- << attribute.annotations@AAAAAAF3ZQrKm4YaqAA= >>
    // ----------- >>
    private Dmas dmas;

    // ----------- << attribute.annotations@AAAAAAF3ZRKIjoa4lt8= >>
    // ----------- >>
    private BoxOfficeInfo boxOfficeInfo;

    // ----------- << attribute.annotations@AAAAAAF3ZRPHa4bQVuA= >>
    // ----------- >>
    private String dettagliParcheggio;

    // ----------- << attribute.annotations@AAAAAAF3ZRdG4Yc2Ncg= >>
    // ----------- >>
    private InfoGeneriche infoGeneriche;

    // ----------- << attribute.annotations@AAAAAAF3ZRyUmoeyqHM= >>
    // ----------- >>
    private EventiInArrivo eventiInArrivo;

    // ----------- << attribute.annotations@AAAAAAF3ZSOhXohOTbw= >>
    // ----------- >>
    private Ada adaContact;

    // ----------- << attribute.annotations@AAAAAAF3cpgwaFrSoJo= >>
    // ----------- >>
    private Citta ;

    // ----------- << attribute.annotations@AAAAAAF3cpmdJmaNsco= >>
    // ----------- >>
    private Stato ;

    // ----------- << attribute.annotations@AAAAAAF3cpuS6nLZCl0= >>
    // ----------- >>
    private Paese ;

    // ----------- << attribute.annotations@AAAAAAF3cpyAgXlD4XI= >>
    // ----------- >>
    private Indirizzo ;

    // ----------- << attribute.annotations@AAAAAAF3cp8GGYrc1ng= >>
    // ----------- >>
    private Location ;

    // ----------- << attribute.annotations@AAAAAAF3cqHhPqPiwqU= >>
    // ----------- >>
    private Set<Mercati>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF3cqTFnbOo23E= >>
    // ----------- >>
    private Set<Dmas>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF3cqbvXsHpvWg= >>
    // ----------- >>
    private BoxOfficeInfo ;

    // ----------- << attribute.annotations@AAAAAAF3cq6W8dC4Et0= >>
    // ----------- >>
    private InfoGeneriche ;

    // ----------- << attribute.annotations@AAAAAAF3crSYzeIHFes= >>
    // ----------- >>
    private Ada ;

    // ----------- << attribute.annotations@AAAAAAF3crgV4f0rR3s= >>
    // ----------- >>
    private EventiInArrivo ;

    private String getNomeLuogo() {
        return nomeLuogo;
    }

    private String getTipoLuogo() {
        return tipoLuogo;
    }

    private String getIdLuogo() {
        return idLuogo;
    }

    private String getUrlLuogo() {
        return urlLuogo;
    }

    private String getCodicePostale() {
        return codicePostale;
    }

    private String getFusoOrario() {
        return fusoOrario;
    }

    private Citta getCitta() {
        return citta;
    }

    private Stato getStato() {
        return stato;
    }

    private Paese getPaese() {
        return paese;
    }

    private Indirizzo getIndirizzo() {
        return indirizzo;
    }

    private Location getLocation() {
        return location;
    }

    private Mercati getMercato() {
        return mercato;
    }

    private Dmas getDmas() {
        return dmas;
    }

    private BoxOfficeInfo getBoxOfficeInfo() {
        return boxOfficeInfo;
    }

    private String getDettagliParcheggio() {
        return dettagliParcheggio;
    }

    private InfoGeneriche getInfoGeneriche() {
        return infoGeneriche;
    }

    private EventiInArrivo getEventiInArrivo() {
        return eventiInArrivo;
    }

    private Ada getAdaContact() {
        return adaContact;
    }

    public Citta get() {
        return ;
    }

    public Stato get() {
        return ;
    }

    public Paese get() {
        return ;
    }

    public Indirizzo get() {
        return ;
    }

    public Location get() {
        return ;
    }

    public Set<Mercati> get() {
        return ;
    }

    public Set<Dmas> get() {
        return ;
    }

    public BoxOfficeInfo get() {
        return ;
    }

    public InfoGeneriche get() {
        return ;
    }

    public Ada get() {
        return ;
    }

    public EventiInArrivo get() {
        return ;
    }

    private void setNomeLuogo(String nomeLuogo) {
        this.nomeLuogo = nomeLuogo;
    }

    private void setTipoLuogo(String tipoLuogo) {
        this.tipoLuogo = tipoLuogo;
    }

    private void setIdLuogo(String idLuogo) {
        this.idLuogo = idLuogo;
    }

    private void setUrlLuogo(String urlLuogo) {
        this.urlLuogo = urlLuogo;
    }

    private void setCodicePostale(String codicePostale) {
        this.codicePostale = codicePostale;
    }

    private void setFusoOrario(String fusoOrario) {
        this.fusoOrario = fusoOrario;
    }

    private void setCitta(Citta citta) {
        this.citta = citta;
    }

    private void setStato(Stato stato) {
        this.stato = stato;
    }

    private void setPaese(Paese paese) {
        this.paese = paese;
    }

    private void setIndirizzo(Indirizzo indirizzo) {
        this.indirizzo = indirizzo;
    }

    private void setLocation(Location location) {
        this.location = location;
    }

    private void setMercato(Mercati mercato) {
        this.mercato = mercato;
    }

    private void setDmas(Dmas dmas) {
        this.dmas = dmas;
    }

    private void setBoxOfficeInfo(BoxOfficeInfo boxOfficeInfo) {
        this.boxOfficeInfo = boxOfficeInfo;
    }

    private void setDettagliParcheggio(String dettagliParcheggio) {
        this.dettagliParcheggio = dettagliParcheggio;
    }

    private void setInfoGeneriche(InfoGeneriche infoGeneriche) {
        this.infoGeneriche = infoGeneriche;
    }

    private void setEventiInArrivo(EventiInArrivo eventiInArrivo) {
        this.eventiInArrivo = eventiInArrivo;
    }

    private void setAdaContact(Ada adaContact) {
        this.adaContact = adaContact;
    }

    public void set(Citta ) {
        this. = ;
    }

    public void set(Stato ) {
        this. = ;
    }

    public void set(Paese ) {
        this. = ;
    }

    public void set(Indirizzo ) {
        this. = ;
    }

    public void set(Location ) {
        this. = ;
    }

    public void set(BoxOfficeInfo ) {
        this. = ;
    }

    public void set(InfoGeneriche ) {
        this. = ;
    }

    public void set(Ada ) {
        this. = ;
    }

    public void set(EventiInArrivo ) {
        this. = ;
    }

    public void link(Citta _) {
        set(_);
    }

    public void link(Stato _) {
        set(_);
    }

    public void link(Paese _) {
        set(_);
    }

    public void link(Indirizzo _) {
        set(_);
    }

    public void link(Location _) {
        set(_);
    }

    public void link(Mercati _) {
        if (_ != null) {
            get().add(_);
        }
    }

    public void link(Dmas _) {
        if (_ != null) {
            get().add(_);
        }
    }

    public void link(BoxOfficeInfo _) {
        set(_);
    }

    public void link(InfoGeneriche _) {
        set(_);
    }

    public void link(Ada _) {
        set(_);
    }

    public void link(EventiInArrivo _) {
        set(_);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }

    public void unlink(Mercati _) {
        if (_ != null) {
            get().remove(_);
        }
    }

    public void unlink(Iterator<Mercati> it) {
        it.remove();
    }

    public void unlink(Dmas _) {
        if (_ != null) {
            get().remove(_);
        }
    }

    public void unlink(Iterator<Dmas> it) {
        it.remove();
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }

    // ----------- << method.annotations@AAAAAAF3ZOLFrIKJlRk= >>
    // ----------- >>
    public Luoghi() {
    // ----------- << method.body@AAAAAAF3ZOLFrIKJlRk= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZOLXPoKPcEY= >>
    // ----------- >>
    public String getNomeLuogo() {
    // ----------- << method.body@AAAAAAF3ZOLXPoKPcEY= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZOLoT4KV2p4= >>
    // ----------- >>
    public String getTipoLuogo() {
    // ----------- << method.body@AAAAAAF3ZOLoT4KV2p4= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZOMK6IKbPtQ= >>
    // ----------- >>
    public String getIdLuogo() {
    // ----------- << method.body@AAAAAAF3ZOMK6IKbPtQ= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZOMiyoKhbVA= >>
    // ----------- >>
    public String getUrlLuogo() {
    // ----------- << method.body@AAAAAAF3ZOMiyoKhbVA= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZOM5WYKnWEE= >>
    // ----------- >>
    public String getCodicePostale() {
    // ----------- << method.body@AAAAAAF3ZOM5WYKnWEE= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZOOPZYKtoyM= >>
    // ----------- >>
    public String getFusoOrario() {
    // ----------- << method.body@AAAAAAF3ZOOPZYKtoyM= >>
    // ----------- >>
    }
    /**
    * @param namePlace
    */

    // ----------- << method.annotations@AAAAAAF3ZOUTOILGEHI= >>
    // ----------- >>
    public void setNomeLuogo(String namePlace) {
    // ----------- << method.body@AAAAAAF3ZOUTOILGEHI= >>
    // ----------- >>
    }
    /**
    * @param Parameter1
    */

    // ----------- << method.annotations@AAAAAAF3ZOUou4LMfu0= >>
    // ----------- >>
    public void setTipoLuogo(String Parameter1) {
    // ----------- << method.body@AAAAAAF3ZOUou4LMfu0= >>
    // ----------- >>
    }
    /**
    * @param idPlace
    */

    // ----------- << method.annotations@AAAAAAF3ZOU4EILSztA= >>
    // ----------- >>
    public void setIdLuogo(String idPlace) {
    // ----------- << method.body@AAAAAAF3ZOU4EILSztA= >>
    // ----------- >>
    }
    /**
    * @param urlPlace
    */

    // ----------- << method.annotations@AAAAAAF3ZOVIo4LY2jQ= >>
    // ----------- >>
    public void setUrlLuogo(String urlPlace) {
    // ----------- << method.body@AAAAAAF3ZOVIo4LY2jQ= >>
    // ----------- >>
    }
    /**
    * @param postalCode
    */

    // ----------- << method.annotations@AAAAAAF3ZOVo0YLe5r0= >>
    // ----------- >>
    public void setCodicePostale(String postalCode) {
    // ----------- << method.body@AAAAAAF3ZOVo0YLe5r0= >>
    // ----------- >>
    }
    /**
    * @param timeZone
    */

    // ----------- << method.annotations@AAAAAAF3ZOV4uILkCCc= >>
    // ----------- >>
    public void setFusoOrario(String timeZone) {
    // ----------- << method.body@AAAAAAF3ZOV4uILkCCc= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZROBy4bE8Lk= >>
    // ----------- >>
    public String getDettagliParcheggio() {
    // ----------- << method.body@AAAAAAF3ZROBy4bE8Lk= >>
    // ----------- >>
    }
    /**
    * @param parking
    */

    // ----------- << method.annotations@AAAAAAF3ZROUd4bKvYs= >>
    // ----------- >>
    public void setDettagliParchrggio(String parking) {
    // ----------- << method.body@AAAAAAF3ZROUd4bKvYs= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3ZNGoM4IfvpY= >>
// ----------- >>
}