/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageLuoghi;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3ZQEFv4VJy/c= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3ZQEFv4VJy/c= >>
// ----------- >>
public class Mercati {
    // ----------- << attribute.annotations@AAAAAAF3ZQGC14V2NYQ= >>
    // ----------- >>
    private String nomeMercato;

    // ----------- << attribute.annotations@AAAAAAF3ZQGTuoV8V2U= >>
    // ----------- >>
    private String idMercato;

    private String getNomeMercato() {
        return nomeMercato;
    }

    private String getIdMercato() {
        return idMercato;
    }

    private void setNomeMercato(String nomeMercato) {
        this.nomeMercato = nomeMercato;
    }

    private void setIdMercato(String idMercato) {
        this.idMercato = idMercato;
    }

    // ----------- << method.annotations@AAAAAAF3ZQGmk4WCW9Y= >>
    // ----------- >>
    public void Mercato() {
    // ----------- << method.body@AAAAAAF3ZQGmk4WCW9Y= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZQG4UYWIhBM= >>
    // ----------- >>
    public String getNomeMercato() {
    // ----------- << method.body@AAAAAAF3ZQG4UYWIhBM= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZQHMDIWOcrM= >>
    // ----------- >>
    public String getIdMercato() {
    // ----------- << method.body@AAAAAAF3ZQHMDIWOcrM= >>
    // ----------- >>
    }
    /**
    * @param marketName
    */

    // ----------- << method.annotations@AAAAAAF3ZQHf5IWUafA= >>
    // ----------- >>
    public void setNomeMercato(String marketName) {
    // ----------- << method.body@AAAAAAF3ZQHf5IWUafA= >>
    // ----------- >>
    }
    /**
    * @param marketId
    */

    // ----------- << method.annotations@AAAAAAF3ZQHzsIWarK0= >>
    // ----------- >>
    public void setIdMercato(String marketId) {
    // ----------- << method.body@AAAAAAF3ZQHzsIWarK0= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3ZQEFv4VJy/c= >>
// ----------- >>
}