/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageLuoghi;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3ZPJbeYPzQhU= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3ZPJbeYPzQhU= >>
// ----------- >>
public class Paese {
    // ----------- << attribute.annotations@AAAAAAF3ZPVsgoQgIL8= >>
    // ----------- >>
    private String nomePaese;

    // ----------- << attribute.annotations@AAAAAAF3ZPV+3IQme7o= >>
    // ----------- >>
    private String codicePaese;

    private String getNomePaese() {
        return nomePaese;
    }

    private String getCodicePaese() {
        return codicePaese;
    }

    private void setNomePaese(String nomePaese) {
        this.nomePaese = nomePaese;
    }

    private void setCodicePaese(String codicePaese) {
        this.codicePaese = codicePaese;
    }

    // ----------- << method.annotations@AAAAAAF3ZPZdF4Qxi/M= >>
    // ----------- >>
    public Paese() {
    // ----------- << method.body@AAAAAAF3ZPZdF4Qxi/M= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZPZrSoQ3+mU= >>
    // ----------- >>
    public String getNomePaese() {
    // ----------- << method.body@AAAAAAF3ZPZrSoQ3+mU= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZPZ3+oQ98M8= >>
    // ----------- >>
    public String getCodicePaese() {
    // ----------- << method.body@AAAAAAF3ZPZ3+oQ98M8= >>
    // ----------- >>
    }
    /**
    * @param countryName
    */

    // ----------- << method.annotations@AAAAAAF3ZPaGSIRDy5c= >>
    // ----------- >>
    public void setNomePaese(String countryName) {
    // ----------- << method.body@AAAAAAF3ZPaGSIRDy5c= >>
    // ----------- >>
    }
    /**
    * @param countryCode
    */

    // ----------- << method.annotations@AAAAAAF3ZPa5z4RJqWo= >>
    // ----------- >>
    public void setCodicePaese(String countryCode) {
    // ----------- << method.body@AAAAAAF3ZPa5z4RJqWo= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3ZPJbeYPzQhU= >>
// ----------- >>
}