/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PackageLuoghi;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3ZO1voIN3LLU= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3ZO1voIN3LLU= >>
// ----------- >>
public class Stato {
    // ----------- << attribute.annotations@AAAAAAF3ZO36HIOlMpM= >>
    // ----------- >>
    private String nomeStato;

    // ----------- << attribute.annotations@AAAAAAF3ZO4L4YOr8Rg= >>
    // ----------- >>
    private String codiceStato;

    private String getNomeStato() {
        return nomeStato;
    }

    private String getCodiceStato() {
        return codiceStato;
    }

    private void setNomeStato(String nomeStato) {
        this.nomeStato = nomeStato;
    }

    private void setCodiceStato(String codiceStato) {
        this.codiceStato = codiceStato;
    }

    // ----------- << method.annotations@AAAAAAF3ZO9BFIO0E9g= >>
    // ----------- >>
    public Stato() {
    // ----------- << method.body@AAAAAAF3ZO9BFIO0E9g= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZO9hMoO7dCs= >>
    // ----------- >>
    public String getNomeStato() {
    // ----------- << method.body@AAAAAAF3ZO9hMoO7dCs= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF3ZO9wUoPBTwc= >>
    // ----------- >>
    public String getCodiceStato() {
    // ----------- << method.body@AAAAAAF3ZO9wUoPBTwc= >>
    // ----------- >>
    }
    /**
    * @param stateName
    */

    // ----------- << method.annotations@AAAAAAF3ZO+Br4PHd3M= >>
    // ----------- >>
    public void setNomeStato(String stateName) {
    // ----------- << method.body@AAAAAAF3ZO+Br4PHd3M= >>
    // ----------- >>
    }
    /**
    * @param stateCode
    */

    // ----------- << method.annotations@AAAAAAF3ZO+PgoPN2H8= >>
    // ----------- >>
    public void setCodiceStato(String stateCode) {
    // ----------- << method.body@AAAAAAF3ZO+PgoPN2H8= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF3ZO1voIN3LLU= >>
// ----------- >>
}